//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PineAPPService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_card
    {
        public decimal Id { get; set; }
        public string ActivationCode { get; set; }
        public string ActivationUrl { get; set; }
        public string Amount { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> CardId { get; set; }
        public string CardNumber { get; set; }
        public string CardPin { get; set; }
        public string LabelProductName { get; set; }
        public string OrderRefNo { get; set; }
        public string Validity { get; set; }
        public string RecepientEmail { get; set; }
        public string ProductSku { get; set; }
        public string ProductTheme { get; set; }
        public string LableCardNumber { get; set; }
        public string LableCardPin { get; set; }
        public string lableValidity { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string EnrptCardNo { get; set; }
        public string EnrptCardPin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
