//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PineService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobEMAILQue
    {
        public Nullable<int> FormNo { get; set; }
        public string EMailBody { get; set; }
        public Nullable<System.DateTime> EmailDate { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
        public string EmailID { get; set; }
        public string EmailType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> RecTimeStamp { get; set; }
        public int ID { get; set; }
        public string FromEmailID { get; set; }
        public string Subject { get; set; }
    }
}
