//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PineService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobFinalSMSQue
    {
        public Nullable<int> JOBSMSQueID { get; set; }
        public string SMSBody { get; set; }
        public Nullable<System.DateTime> SMSDate { get; set; }
        public Nullable<bool> IsSMSSent { get; set; }
        public Nullable<decimal> mobileno { get; set; }
        public string SMSType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> RecTimeStamp { get; set; }
        public Nullable<bool> IsError { get; set; }
        public int ID { get; set; }
    }
}
