//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PineService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public decimal Id { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string code { get; set; }
        public string OrderRefNo { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
