//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinelabconsol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingAddress
    {
        public decimal Id { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string lastname { get; set; }
        public string AddLineOne { get; set; }
        public string AddLineTwo { get; set; }
        public string PostCode { get; set; }
        public string State { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string OrderId { get; set; }
    }
}
