//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinelabconsol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarteDetail
    {
        public decimal Id { get; set; }
        public string ProductSku { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string PriceType { get; set; }
        public Nullable<decimal> ProdPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string currencyCode { get; set; }
        public string Posted { get; set; }
    }
}
