//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinelabconsol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public decimal Id { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public string Logo { get; set; }
        public Nullable<decimal> CreditPoint { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string ContactName { get; set; }
        public string ContactNo1 { get; set; }
        public string ContactNo2 { get; set; }
        public string ContactEmail1 { get; set; }
        public string ContactEmail2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CompanyAccountName { get; set; }
        public string CompanyBankName { get; set; }
        public string CompanyAccountType { get; set; }
        public string CompanyAccountNumber { get; set; }
        public string CompanyIFSCCode { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConsumerKey { get; set; }
        public string ConsumerSecret { get; set; }
        public string AuthToken { get; set; }
        public Nullable<System.DateTime> AuthTokenGeneationDate { get; set; }
    }
}
