//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinelabconsol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public decimal Id { get; set; }
        public string thumbnail { get; set; }
        public string mobile { get; set; }
        public string @base { get; set; }
        public string small { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ProductId { get; set; }
        public string CategoryId { get; set; }
    }
}
