//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinelabconsol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messgeApi
    {
        public int id { get; set; }
        public string msgapi { get; set; }
        public string username { get; set; }
        public string passwrd { get; set; }
        public string SenderId { get; set; }
        public string Activests { get; set; }
        public int cmpid { get; set; }
        public string Memusername { get; set; }
        public string CompWeb { get; set; }
        public string mlmurl { get; set; }
        public string ShopingPortal { get; set; }
        public string AirTicket { get; set; }
        public string cmplogo { get; set; }
        public string favicn { get; set; }
        public string IsPromo { get; set; }
        public string IsFlight { get; set; }
        public string IsLoginOTP { get; set; }
        public string IsServiceOTP { get; set; }
        public string LoginAPI { get; set; }
        public string BalanceCheckAPI { get; set; }
        public string GetBalAPI { get; set; }
        public string sts { get; set; }
        public string PortalType { get; set; }
        public string MobileApp { get; set; }
    }
}
