//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinelabconsol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public decimal Id { get; set; }
        public string sku { get; set; }
        public string url { get; set; }
        public string name { get; set; }
        public Nullable<decimal> minPrice { get; set; }
        public Nullable<decimal> maxPrice { get; set; }
        public string code { get; set; }
        public string symbol { get; set; }
        public string numericCode { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string categoryId { get; set; }
    }
}
