//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pinelabconsol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDiscount
    {
        public decimal Id { get; set; }
        public string ProductSku { get; set; }
        public string DiscountType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string DiscountDesc { get; set; }
        public string CounponCode { get; set; }
        public Nullable<int> CouponPriority { get; set; }
    }
}
