//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PineLabsShoppingPortal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PineLabsShoppingPortal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CartDetailWithPayment.
        /// </summary>
        public static string CartDetailWithPayment {
            get {
                return ResourceManager.GetString("CartDetailWithPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categoryId.
        /// </summary>
        public static string categoryId {
            get {
                return ResourceManager.GetString("categoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckoutPage.
        /// </summary>
        public static string CheckoutPage {
            get {
                return ResourceManager.GetString("CheckoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE.
        /// </summary>
        public static string PriceTypeRange {
            get {
                return ResourceManager.GetString("PriceTypeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLAB.
        /// </summary>
        public static string PriceTypeSlab {
            get {
                return ResourceManager.GetString("PriceTypeSlab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductDetailBySku.
        /// </summary>
        public static string ProductDetailBySku {
            get {
                return ResourceManager.GetString("ProductDetailBySku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductListByFilter.
        /// </summary>
        public static string ProductListByFilter {
            get {
                return ResourceManager.GetString("ProductListByFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShoppingCartDetailPage.
        /// </summary>
        public static string ShoppingCartDetailPage {
            get {
                return ResourceManager.GetString("ShoppingCartDetailPage", resourceCulture);
            }
        }
    }
}
